name: Docker CI/CD

on:
  push:
    branches:
      - main  # You can adjust this to any branch you prefer

jobs:
  build:
    runs-on: ubuntu:22.04

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker to build the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build the Docker image and tag it as 'latest'
      - name: Build Docker image
        run: docker build -t fastapi-house-price .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Tag and push the image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag fastapi-house-price:latest ${{ secrets.DOCKER_USERNAME }}/mlOps:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mlOps:latest


  