name: Docker CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform builds (if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Secret set in GitHub settings
          password: ${{ secrets.DOCKER_PASSWORD }}  # Secret set in GitHub settings

      # Build the Docker image
      - name: Build Docker image
        run: docker compose build ml_model

      # Tag the Docker image with the desired tags
      - name: Tag Docker image
        run: docker tag ml_model gaspards/mlops:latest

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push gaspards/mlops
