name: Docker CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform builds (optional, you can skip if not needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image from the Dockerfile at the root
      - name: Build Docker image
        run: docker build -t gaspards/mlops:latest .

      # Tag the Docker image with the latest commit SHA
      - name: Tag Docker image
        run: docker tag gaspards/mlops:latest gaspards/mlops:${{ github.sha }}

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push gaspards/mlops
          docker push gaspards/mlops:${{ github.sha }}

          # Install sshpass
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Deploy to the remote server via sshpass and Docker commands
      - name: Deploy to VM
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ubuntu@20.86.55.5
            docker pull gaspards/mlops:latest &&
            docker rm -f my_app_gaspard || true &&
            docker run -d --name my_app_gaspard -p 8096:8000 gaspards/mlops:latest
