name: Docker CI/CD

on:
  push:
    branches:
      - main  # You can adjust this to any branch you prefer

jobs:
  build:
    runs-on: ubuntu:22.04

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker to build the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            Gaspard-s/mlOps:latest
            Gaspard-s/mlOps:${{ github.sha }}

  