name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t gaspards/mlops:latest .

      - name: Tag Docker image
        run: docker tag gaspards/mlops:latest gaspards/mlops:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push gaspards/mlops
          docker push gaspards/mlops:${{ github.sha }}

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VM
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ubuntu@20.86.55.5 "docker pull gaspards/mlops:latest && \
            docker rm -f my_app_gaspard || true && \
            docker run -d --name my_app_gaspard -p 8096:8000 gaspards/mlops:latest"

